-- Inspect how a table and its indexes map to CockroachDB ranges.
SHOW RANGES FROM TABLE orders WITH DETAILS;
SHOW RANGES FROM INDEX orders@orders_created_at_idx WITH DETAILS;

-- See whether execution stays near one range or distributes across nodes.
EXPLAIN (DISTSQL, VERBOSE)
SELECT customer_id, sum(total_cents)
FROM orders
WHERE created_at >= now() - INTERVAL '1 day'
GROUP BY customer_id;

-- Preserve a sequential business number while distributing its write index.
CREATE TABLE order_events (
    event_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    order_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload JSONB NOT NULL,
    PRIMARY KEY (event_id) USING HASH WITH (bucket_count = 8),
    INDEX order_events_by_order (order_id, created_at DESC)
);

-- Recheck both write distribution and read plans after representative load.
SHOW RANGES FROM TABLE order_events WITH DETAILS;
EXPLAIN (OPT, VERBOSE)
SELECT payload
FROM order_events
WHERE order_id = $1
ORDER BY created_at DESC
LIMIT 50;
