'use client';

import { useState } from 'react';
type Protocol = 'HTTP/1.1' | 'HTTP/2' | 'HTTP/3';
export default function HttpProtocolPerformance() {
  const [concurrentStreams, setConcurrentStreams] = useState(100); const [resourceCount, setResourceCount] = useState(50); const [networkLatency, setNetworkLatency] = useState(100); const [protocolVersion, setProtocolVersion] = useState<Protocol>('HTTP/2');
  const http1Connections = Math.min(6, resourceCount); const connections = protocolVersion === 'HTTP/1.1' ? http1Connections : 1; const http1Latency = Math.ceil(resourceCount / http1Connections) * networkLatency; const http2Latency = networkLatency + (Math.ceil(resourceCount / concurrentStreams) - 1) * 10; const totalLatency = protocolVersion === 'HTTP/1.1' ? http1Latency : protocolVersion === 'HTTP/2' ? http2Latency : Math.round(http2Latency * 0.8); const headerSize = protocolVersion === 'HTTP/1.1' ? 800 : protocolVersion === 'HTTP/2' ? 50 : 30; const headerOverheadKB = (resourceCount * headerSize) / 1024; const performanceScore = Math.max(0, Math.round(100 - (totalLatency / 1000) * 10 - headerOverheadKB / 10)); const multiplexingEfficiency = protocolVersion === 'HTTP/1.1' ? 16 : protocolVersion === 'HTTP/2' ? 85 : 95;
  return <section className="rounded-lg border border-neutral-200 bg-white p-6 shadow-card dark:border-neutral-800 dark:bg-neutral-900"><h2 className="mb-4 text-xl font-semibold">HTTP Protocol Performance Calculator</h2><div className="grid gap-6 md:grid-cols-2"><div className="space-y-4"><div><label htmlFor="http-protocol" className="mb-1 block text-sm font-medium">Protocol Version</label><select id="http-protocol" value={protocolVersion} onChange={(event) => setProtocolVersion(event.target.value as Protocol)} className="w-full rounded-lg border bg-white p-2 dark:bg-neutral-800"><option>HTTP/1.1</option><option>HTTP/2</option><option>HTTP/3</option></select></div><Range id="http-resources" label={`Resources to Load: ${resourceCount}`} min={10} max={200} step={10} value={resourceCount} onChange={setResourceCount} /><Range id="http-latency" label={`Network Latency: ${networkLatency}ms`} min={10} max={500} step={10} value={networkLatency} onChange={setNetworkLatency} />{protocolVersion !== 'HTTP/1.1' ? <Range id="http-streams" label={`Concurrent Streams: ${concurrentStreams}`} min={10} max={256} step={10} value={concurrentStreams} onChange={setConcurrentStreams} /> : null}</div><div className="grid grid-cols-2 gap-4 content-start"><Metric label="Total Load Time" value={`${totalLatency}ms`} /><Metric label="Connections" value={connections.toString()} /><Metric label="Compression" value={protocolVersion === 'HTTP/1.1' ? '0%' : protocolVersion === 'HTTP/2' ? '85%' : '90%'} /><Metric label="Performance" value={performanceScore.toString()} /></div></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Detail label="Header Overhead" value={`${headerOverheadKB.toFixed(1)}KB`} /><Detail label="Multiplexing" value={`${multiplexingEfficiency}%`} /><Detail label="Requests/sec" value={Math.round(1000 / (totalLatency / resourceCount)).toString()} /></div></section>;
}
function Range({ id, label, min, max, step, value, onChange }: { id: string; label: string; min: number; max: number; step: number; value: number; onChange: (value: number) => void }) { return <div><label htmlFor={id} className="mb-1 block text-sm font-medium">{label}</label><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="w-full" /></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-blue-100 p-4 text-center text-blue-700 dark:bg-blue-900/30 dark:text-blue-300"><div className="text-2xl font-bold">{value}</div><div className="text-sm">{label}</div></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-neutral-50 p-3 dark:bg-neutral-800"><p className="text-sm"><strong>{label}:</strong> {value}</p></div>; }
