stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - data/raw
      - src/prepare.py
    params:
      - prepare.test_fraction
      - prepare.seed
    outs:
      - data/prepared

  train:
    cmd: python src/train.py
    deps:
      - data/prepared
      - src/train.py
    params:
      - train.max_depth
      - train.seed
    outs:
      - models/classifier.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/classifier.pkl
      - data/prepared
      - src/evaluate.py
    metrics:
      - reports/metrics.json:
          cache: false
