---
all:
  children:
    webservers:
      hosts:
        web-a1.example.net:
          availability_zone: zone-a
        web-a2.example.net:
          availability_zone: zone-a
        web-b1.example.net:
          availability_zone: zone-b
        web-b2.example.net:
          availability_zone: zone-b
        web-c1.example.net:
          availability_zone: zone-c
        web-c2.example.net:
          availability_zone: zone-c
        stage-a1.example.net:
          availability_zone: zone-a
        stage-b1.example.net:
          availability_zone: zone-b

    production:
      hosts:
        web-a1.example.net:
        web-a2.example.net:
        web-b1.example.net:
        web-b2.example.net:
        web-c1.example.net:
        web-c2.example.net:

    staging:
      hosts:
        stage-a1.example.net:
        stage-b1.example.net:

    canary:
      hosts:
        web-a1.example.net:
        web-b1.example.net:
